goog.provide('commands');


/** @enum {string} */
commands.Type = {
  PAINT_SUPER: 'paintSuper',
  SAVE: 'save',
  RESTORE: 'restore',
  SCALE: 'scale',
  ROTATE: 'rotate',
  TRANSLATE: 'translate',
  TRANSFORM: 'transform',
  SET_TRANSFORM: 'setTransform',
  RESET_TRANSFORM: 'resetTransform',
  CLEAR_RECT: 'clearRect',
  FILL_RECT: 'fillRect',
  STROKE_RECT: 'strokeRect',
  BEGIN_PATH: 'beginPath',
  CLOSE_PATH: 'closePath',
  MOVE_TO: 'moveTo',
  LINE_TO: 'lineTo',
  QUADRATIC_CURVE_TO: 'quadraticCurveTo',
  BEZIER_CURVE_TO: 'bezierCurveTo',
  ARC_TO: 'arcTo',
  RECT: 'rect',
  ARC: 'arc',
  FILL: 'fill',
  STROKE: 'stroke',
  CLIP: 'clip',
  FILL_TEXT: 'fillText',
  STROKE_TEXT: 'strokeText',
  LINE_DASH: 'lineDash',
  ALPHA: 'globalAlpha',
  COMPOSITE_OPERATION: 'globalCompositeOperation',
  SHADOW_OFFSET_X: 'shadowOffsetX',
  SHADOW_OFFSET_Y: 'shadowOffsetY',
  SHADOW_BLUR: 'shadowBlur',
  SHADOW_COLOR: 'shadowColor',
  STROKE_COLOR: 'strokeStyle',
  FILL_COLOR: 'fillStyle',
  LINE_WIDTH: 'lineWidth',
  LINE_CAP: 'lineCap',
  LINE_JOIN: 'lineJoin',
  MITER_LIMIT: 'miterLimit',
  FONT: 'font',
  TEXT_ALIGN: 'textAlign',
  TEXT_BASELINE: 'textBaseline'
};
