// This file was autogenerated by ../bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/canvas.js', ['canvas'], ['commands', 'goog.asserts', 'goog.object', 'svg'], false);
goog.addDependency('../../../../src/commands.js', ['commands'], [], false);
goog.addDependency('../../../../src/css.js', ['css'], ['cssom', 'goog.functions'], false);
goog.addDependency('../../../../src/css_test.js', ['css_test'], ['css', 'goog.testing.jsunit'], false);
goog.addDependency('../../../../src/cssom.js', ['cssom'], ['goog.asserts'], false);
goog.addDependency('../../../../src/cssom_test.js', ['cssom_test'], ['cssom', 'goog.testing.jsunit'], false);
goog.addDependency('../../../../src/paint.js', ['paint'], ['canvas'], false);
goog.addDependency('../../../../src/pipeline.js', ['pipeline'], ['paint', 'style'], false);
goog.addDependency('../../../../src/style.js', ['style'], ['css'], false);
goog.addDependency('../../../../src/svg.js', ['svg'], ['commands', 'goog.asserts'], false);
