// This file was autogenerated by ../bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/css-poly.js', ['cssom'], []);
goog.addDependency('../../../../src/css.js', ['css'], ['cssom']);
goog.addDependency('../../../../src/css_test.js', ['css_test'], ['css', 'goog.testing.jsunit']);
goog.addDependency('../../../../src/cssom.js', ['cssom'], ['goog.asserts']);
goog.addDependency('../../../../src/cssom_test.js', ['cssom_test'], ['cssom', 'goog.testing.jsunit']);
