// This file was autogenerated by ../bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/canvas.js', ['canvas'], ['goog.asserts']);
goog.addDependency('../../../../src/css.js', ['css'], ['cssom', 'goog.functions']);
goog.addDependency('../../../../src/css_test.js', ['css_test'], ['css', 'goog.testing.jsunit']);
goog.addDependency('../../../../src/cssom.js', ['cssom'], ['goog.asserts']);
goog.addDependency('../../../../src/cssom_test.js', ['cssom_test'], ['cssom', 'goog.testing.jsunit']);
goog.addDependency('../../../../src/paint.js', ['paint'], ['canvas']);
goog.addDependency('../../../../src/pipeline.js', ['pipeline'], ['paint', 'style']);
goog.addDependency('../../../../src/style.js', ['style'], ['css']);
